"""add models for payment, category; extend item model

Revision ID: 08317091e4a8
Revises: d4867f3a4c0a
Create Date: 2020-11-14 23:54:46.997514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08317091e4a8'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_title'), 'payment', ['title'], unique=False)
    op.add_column('item', sa.Column('_date_created', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('_date_modified', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.drop_index('ix_item_title', table_name='item')
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'item', 'payment', ['payment_id'], ['id'])
    op.drop_column('item', 'title')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.drop_column('item', 'payment_id')
    op.drop_column('item', 'is_deleted')
    op.drop_column('item', 'date')
    op.drop_column('item', 'category_id')
    op.drop_column('item', 'amount')
    op.drop_column('item', '_date_modified')
    op.drop_column('item', '_date_created')
    op.drop_index(op.f('ix_payment_title'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
