"""add db columns for translations

Revision ID: 372d7f5a5055
Revises: 729a98e30119
Create Date: 2021-12-10 22:21:23.538043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372d7f5a5055'
down_revision = '729a98e30119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('title_en', sa.String(length=30), nullable=True))
    op.add_column('category', sa.Column('title_de', sa.String(length=30), nullable=True))
    op.drop_index('ix_category_name', table_name='category')
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_title_de'), 'category', ['title_de'], unique=False)
    op.create_index(op.f('ix_category_title_en'), 'category', ['title_en'], unique=False)
    op.drop_column('category', 'name')
    op.add_column('itemtype', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('itemtype', sa.Column('title_de', sa.String(), nullable=True))
    op.drop_index('ix_itemtype_name', table_name='itemtype')
    op.create_unique_constraint(None, 'itemtype', ['title_de'])
    op.create_unique_constraint(None, 'itemtype', ['title_en'])
    op.drop_column('itemtype', 'name')
    op.add_column('payment', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('title_de', sa.String(), nullable=True))
    op.drop_index('ix_payment_name', table_name='payment')
    op.create_unique_constraint(None, 'payment', ['title_en'])
    op.create_unique_constraint(None, 'payment', ['title_de'])
    op.drop_column('payment', 'name')
    op.add_column('user', sa.Column('default_locale', sa.String(length=2), nullable=True))
    op.create_unique_constraint(None, 'user', ['default_locale'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'default_locale')
    op.add_column('payment', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.create_index('ix_payment_name', 'payment', ['name'], unique=False)
    op.drop_column('payment', 'title_de')
    op.drop_column('payment', 'title_en')
    op.add_column('itemtype', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'itemtype', type_='unique')
    op.drop_constraint(None, 'itemtype', type_='unique')
    op.create_index('ix_itemtype_name', 'itemtype', ['name'], unique=False)
    op.drop_column('itemtype', 'title_de')
    op.drop_column('itemtype', 'title_en')
    op.add_column('category', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_category_title_en'), table_name='category')
    op.drop_index(op.f('ix_category_title_de'), table_name='category')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.drop_column('category', 'title_de')
    op.drop_column('category', 'title_en')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###
