"""remove uniqueness for title_x cols

Revision ID: e05e028c9a3d
Revises: 372d7f5a5055
Create Date: 2021-12-10 22:35:06.789635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05e028c9a3d'
down_revision = '372d7f5a5055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('itemtype_title_de_key', 'itemtype', type_='unique')
    op.drop_constraint('itemtype_title_en_key', 'itemtype', type_='unique')
    op.create_index(op.f('ix_itemtype_title_de'), 'itemtype', ['title_de'], unique=False)
    op.create_index(op.f('ix_itemtype_title_en'), 'itemtype', ['title_en'], unique=False)
    op.drop_constraint('payment_title_de_key', 'payment', type_='unique')
    op.drop_constraint('payment_title_en_key', 'payment', type_='unique')
    op.create_index(op.f('ix_payment_title_de'), 'payment', ['title_de'], unique=False)
    op.create_index(op.f('ix_payment_title_en'), 'payment', ['title_en'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_title_en'), table_name='payment')
    op.drop_index(op.f('ix_payment_title_de'), table_name='payment')
    op.create_unique_constraint('payment_title_en_key', 'payment', ['title_en'])
    op.create_unique_constraint('payment_title_de_key', 'payment', ['title_de'])
    op.drop_index(op.f('ix_itemtype_title_en'), table_name='itemtype')
    op.drop_index(op.f('ix_itemtype_title_de'), table_name='itemtype')
    op.create_unique_constraint('itemtype_title_en_key', 'itemtype', ['title_en'])
    op.create_unique_constraint('itemtype_title_de_key', 'itemtype', ['title_de'])
    # ### end Alembic commands ###
