"""rename title column of categories/payments table

Revision ID: 18a953a4b666
Revises: 464d6d4b717a
Create Date: 2020-11-15 21:26:01.643971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18a953a4b666'
down_revision = '464d6d4b717a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_index('ix_category_title', table_name='category')
    op.drop_column('category', 'title')
    op.alter_column('item', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('payment', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_payment_name'), 'payment', ['name'], unique=True)
    op.drop_index('ix_payment_title', table_name='payment')
    op.drop_column('payment', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_payment_title', 'payment', ['title'], unique=True)
    op.drop_index(op.f('ix_payment_name'), table_name='payment')
    op.drop_column('payment', 'name')
    op.alter_column('item', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('category', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_category_title', 'category', ['title'], unique=True)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
