"""add more constraints

Revision ID: 1e9a8959155d
Revises: 18a953a4b666
Create Date: 2020-11-15 22:13:26.415272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e9a8959155d'
down_revision = '18a953a4b666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.alter_column('item', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('item', '_date_modified')
    op.drop_column('item', '_date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('_date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('_date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('item', 'removed_at')
    op.drop_column('item', 'modified_at')
    op.drop_column('item', 'created_at')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
